### ISSUE TITLE
https://web-api.coinmarketcap.com/v1/cryptocurrency/map no longer works?

### ISSUE THREAD

**Issue by andreltr** [sstoeckl/crypto2#20] opened 2024-05-28 22:26 UTC
Hello,

The get the error below trying to test this library:

R> library(crypto2)
R> library(dplyr)
R> # List all active coins
R> coins <- crypto_list(only_active=TRUE)
Error in open.connection(con, "rb") : 
  cannot open the connection to 'https://web-api.coinmarketcap.com/v1/cryptocurrency/map'
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'https://web-api.coinmarketcap.com/v1/cryptocurrency/map': HTTP status was '404 Not Found'

How to solve it, please?

TIA

**Comment by sstoeckl** [comment] 2024-05-29 08:37
Unfortunately, this seems to be the case. In this case the package is no longer useful. I have to investigate...

**Comment by manovG** [comment] 2024-06-04 16:49
Fingers crossed for resolving the bug.
The package is very useful and I am looking forward to use it again.

I've got to the same error message as  andreltr...

**Comment by sstoeckl** [comment] 2024-06-11 23:39
I have pushed a fix to github and all functions should be working again. @manovG  and @andreltr pleas test, if it works I will submit the package to CRAN this weekend.

**Comment by manovG** [comment] 2024-06-16 06:31
Hello again.
Everything working now!
Many thanks for your effort and support for this package!

**Comment by Spock23** [comment] 2024-07-02 10:34
Hi,

I am getting the following: 

Error: Unfortunately, the scraper could not find data with the sent api-call. If you believe this is a bug please report at https://github.com/sstoeckl/crypto2/issues

Thanks a lot in advance.

**Comment by sstoeckl** [comment] 2024-07-02 14:00
@Spock23 I cannt say what happened if you do not deliver any details on what you exactly did to cause this error. Can you please be clearer on that? Ideally some reproducible example.
Best regards

**Comment by Spock23** [comment] 2024-07-02 14:06
Hi,

Running the following on latest R 4.4.1 version:

 install.packages("devtools")
devtools::install_github("sstoeckl/crypto2")
library(crypto2)

library(dplyr)
 install.packages("coinmarketcapr")
library(coinmarketcapr)

 List all active coins
coins <- crypto_list(only_active=TRUE)
 retrieve information for all (the first 3) of those coins
coin_info <- crypto_info(coins,limit=3)

Output error:
Error: Unfortunately, the scraper could not find data with the sent api-call. If you believe this is a bug please report at https://github.com/sstoeckl/crypto2/issues

**Comment by sstoeckl** [comment] 2024-07-02 17:04
API change. Fixed with release v2.0.1 (on its way to CRAN)

**Closed as completed by sstoeckl** 2024-07-02 17:04 UTC
Labels: bug
